# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(384, 217)
        dialog.setMinimumSize(QtCore.QSize(384, 217))
        dialog.setMaximumSize(QtCore.QSize(384, 217))
        dialog.setStyleSheet("QDialog{\n"
"  background-color: #fff;\n"
"  color: #fff;\n"
"}\n"
"QPushButton{\n"
"  background-color: #fff;\n"
"  color: #fff;\n"
" border:0px;\n"
"}")
        self.l1 = QtWidgets.QLabel(parent=dialog)
        self.l1.setGeometry(QtCore.QRect(10, 70, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color: rgb(155, 191, 215);\n"
"font: 75 24pt \"Bahnschrift Condensed\";")
        self.l1.setObjectName("l1")
        self.label_2 = QtWidgets.QLabel(parent=dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 56, 41))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"Bahnschrift\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=dialog)
        self.label_5.setGeometry(QtCore.QRect(73, 12, 16, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.playButton = QtWidgets.QPushButton(parent=dialog)
        self.playButton.setGeometry(QtCore.QRect(10, 140, 227, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(99)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"  background-color: rgb(155, 191, 215);\n"
"  color: rgb(255, 255, 255);\n"
"  font-weight: 900;\n"
"  border-radius: 8px;\n"
"  border: 1px solid rgb(137, 169, 190);\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(137, 169, 190);\n"
"  border: 3px solid rgb(155, 191, 215);\n"
"}")
        self.playButton.setObjectName("playButton")
        self.label_6 = QtWidgets.QLabel(parent=dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(34)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 34pt \"Bahnschrift Condensed\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(parent=dialog)
        self.label.setGeometry(QtCore.QRect(13, 58, 227, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=dialog)
        self.label_4.setGeometry(QtCore.QRect(315, 58, 16, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Меню"))
        self.l1.setText(_translate("dialog", "Игра \"Сапёр\""))
        self.label_2.setText(_translate("dialog", "Версия: 1.0"))
        self.playButton.setText(_translate("dialog", "Играть"))
        self.label_6.setText(_translate("dialog", "Добро пожаловать!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec())
